name: test_widgets_with_size
description: A flutter utilitary package to make easier the process of testing widgets on diferent device sizes
version: 1.0.1+4
homepage: https://github.com/rodrigobastosv/test_widgets_with_size

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
